#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# update package repository
sudo apt-get -y update

# install haproxy
sudo apt-get -y install haproxy

# make User the owner of config file
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

# ensure haproxy run immediately on boot
echo "ENABLED=1" | sudo tee --append /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend lawre.tech
        timeout client 30000
        bind *:80
		mode http
        default_backend app

backend app
        balance roundrobin
        server 451414-web-01 54.209.26.149:80 check
        server 451414-web-02 54.175.243.246:80 check
EOT

sudo service haproxy restart
