#!/usr/bin/env bash
# nginx listens on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i '/listen \[::\]:80 default_server;/a \\tlisten 80 default_server;' /etc/nginx/sites-available/default

