#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
#Your script should only display:

    #username
    #user id
    #Home directory path for the user
#!/bin/bash

file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home_directory _;
do
    echo "$username:$uid:$home_directory"
done < "$file"
