#!/usr/bin/env bash
#This script displays "Best School" 10 times
#For 9th time it also prints "Hi"
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ "$count" -eq 9 ]
    then
        echo "Hi"
    fi
	count=$((count + 1))
done
