#!/usr/bin/env bash
# make the apache server return Hello Holberton when querying the root
# Exit immediately if a command exits with a non-zero status
set -e

# Update package list
sudo apt-get -y update

# Install Apache2
sudo apt-get install -y apache2

# Start Apache2 service
sudo service apache2 start

# Create index.html with "Hello Holberton" text
echo "Hello Holberton" | sudo tee /var/www/html/index.html

# Restart Apache2 service to apply changes
sudo service apache2 restart

echo "Apache has been successfully installed, configured, and restarted."

