#!/usr/bin/env bash
# run program as root
# Check if the script is run with sufficient arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run 'whoami' as the specified user
sudo -u "$1" whoami

