#!/usr/bin/env bash
# Run nginx as a different user(nginx) and not as root

# Modify nginx to run as user 'nginx'
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change port 80 to 8080 in the default site configuration
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Set proper permissions for the nginx configuration file
sudo chmod 644 /etc/nginx/nginx.conf

# Kill the Apache process
sudo kill "$(pgrep 'apache2' | head -1)"

# Restart nginx as user 'nginx'
sudo service nginx restart


